[package]
name = "magpie-fuzzing"
version = "0.0.0"
authors = ["Emil Englesson <englesson.emil@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
